### PR TITLE
Updat zh_cn.json

### PR DESCRIPTION
**Pull request by Aemande123**
Update zh_cn.json 1.14.4

In addition
Can I repost your mods to mcbbs?
mcbbs:https://www.mcbbs.net/
mcbbs is the largest minecraft fan forum in China.

I will not provide download sources other than Curseforge

I'm sorry to ask questions here, because of GFW, I cannot register for a twitch account, so I cannot ask questions on Curseforge.

### CODE REVIEW

**Comment by OribiaDev** [comment]
you can put it on there as long as you don't host the mod file. Just make sure you provide a Link to the original modpage. I give you permission to add my mod to that page.

**Comment by Aemande123** [comment]
> you can put it on there as long as you don't host the mod file. Just make sure you provide a Link to the original modpage. I give you permission to add my mod to that page.

Thank you very much!
I will not provide links other than curseforge and github.

**Comment by a5161655** [comment]
我可以更新一下语言文件吗？
can I update zh_cn?

**Comment by Aemande123** [comment]
> 我可以更新一下语言文件吗？
> can I update zh_cn?

条目并没有增加，当然要改词的话请随意

**Pull request closed without merging**
